# Generated by Django 6.0.1 on 2026-01-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('tired', 'Tired'), ('anxious', 'Anxious'), ('stressed', 'Stressed'), ('lazy', 'Lazy'), ('sad', 'Sad'), ('neutral', 'Neutral')], max_length=20)),
                ('habit_text', models.CharField(max_length=255)),
                ('estimated_time', models.IntegerField(help_text='Estimated time in minutes (1-5)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
